-- ============================================================
-- P101 點閱數系統 Clean Reset SQL
-- 適用：Supabase PostgreSQL
-- 功能：刪除舊版 P101 counter 相關物件，重新建立乾淨一致的資料表、函數、權限與 RLS。
-- 注意：本 SQL 會刪除舊點閱資料。
-- ============================================================

-- 1. Drop old RPC functions first
DROP FUNCTION IF EXISTS public.p101_increment_counter(text, text, text);
DROP FUNCTION IF EXISTS public.p101_increment_counter(text, text, text, text);
DROP FUNCTION IF EXISTS public.p101_get_counters();

-- 2. Drop old tables with possibly inconsistent schemas
DROP TABLE IF EXISTS public."TblP101ViewEvents" CASCADE;
DROP TABLE IF EXISTS public."TblP101ViewCounters" CASCADE;
DROP TABLE IF EXISTS public."TblP101Events" CASCADE;
DROP TABLE IF EXISTS public."TblP101Counters" CASCADE;

-- 3. Create canonical counter table
CREATE TABLE public."TblP101Counters" (
  counter_key text PRIMARY KEY,
  project_code text NOT NULL DEFAULT 'P101',
  target_type text NOT NULL CHECK (target_type IN ('page', 'version')),
  version_code text,
  target_title text NOT NULL,
  target_url text,
  view_count bigint NOT NULL DEFAULT 0 CHECK (view_count >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 4. Create canonical event log table
CREATE TABLE public."TblP101Events" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  counter_key text NOT NULL REFERENCES public."TblP101Counters"(counter_key) ON DELETE CASCADE,
  project_code text NOT NULL DEFAULT 'P101',
  target_type text NOT NULL CHECK (target_type IN ('page', 'version')),
  version_code text,
  referrer text,
  session_id text,
  user_agent text,
  clicked_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX "idx_TblP101Events_counter_key" ON public."TblP101Events"(counter_key);
CREATE INDEX "idx_TblP101Events_clicked_at" ON public."TblP101Events"(clicked_at DESC);

-- 5. Seed counters
INSERT INTO public."TblP101Counters"
  (counter_key, project_code, target_type, version_code, target_title, target_url, view_count)
VALUES
  ('P101_MAIN_PAGE', 'P101', 'page', NULL, '智慧商情研究室入口主頁', NULL, 0),
  ('P101_V01', 'P101', 'version', 'V01', 'P101 校園空間查詢系統 V01', NULL, 0),
  ('P101_V02', 'P101', 'version', 'V02', 'P101 校園空間查詢系統 V02', 'https://liu-ming-yi.github.io/CampusMap01', 0)
ON CONFLICT (counter_key) DO NOTHING;

-- 6. Create canonical RPC function used by assets/app.js
CREATE FUNCTION public.p101_increment_counter(
  p_counter_key text,
  p_referrer text DEFAULT NULL,
  p_session_id text DEFAULT NULL
)
RETURNS TABLE (
  counter_key text,
  view_count bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_target_type text;
  v_version_code text;
  v_view_count bigint;
BEGIN
  -- Lock and update exactly one known counter.
  UPDATE public."TblP101Counters" AS c
  SET view_count = c.view_count + 1,
      updated_at = now()
  WHERE c.counter_key = p_counter_key
  RETURNING c.target_type, c.version_code, c.view_count
  INTO v_target_type, v_version_code, v_view_count;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unknown P101 counter_key: %', p_counter_key
      USING ERRCODE = '22023';
  END IF;

  INSERT INTO public."TblP101Events"
    (counter_key, project_code, target_type, version_code, referrer, session_id, user_agent)
  VALUES
    (p_counter_key, 'P101', v_target_type, v_version_code, p_referrer, p_session_id, NULL);

  RETURN QUERY
  SELECT p_counter_key::text AS counter_key, v_view_count::bigint AS view_count;
END;
$$;

-- 7. Enable RLS
ALTER TABLE public."TblP101Counters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP101Events" ENABLE ROW LEVEL SECURITY;

-- 8. Public read policy for counters
CREATE POLICY "P101 counters are publicly readable"
ON public."TblP101Counters"
FOR SELECT
TO anon, authenticated
USING (true);

-- 9. Direct event insert policy is optional; RPC uses SECURITY DEFINER.
-- Keep direct table writing closed by not creating an INSERT policy.

-- 10. Grants
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public."TblP101Counters" TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.p101_increment_counter(text, text, text) TO anon, authenticated;

-- 11. Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';

-- 12. Verification queries
-- SELECT * FROM public."TblP101Counters" ORDER BY counter_key;
-- SELECT * FROM public.p101_increment_counter('P101_MAIN_PAGE', NULL, 'test-session');
-- SELECT * FROM public."TblP101Events" ORDER BY id DESC LIMIT 5;
